---
title: "조건부 확률과 함께 연결된 몇가지"
output: 
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 조건부 확률

표본공간 $\Omega$ 상의 두 사건 $A$와 $B$에 대해 조건부 확률 $P(A|B)$는 각각 다음과 같이 정의합니다.

<p align="center">$P(A|B) = \frac{P(A \cap B)}{P(B)}$</p>

여기서 우변의 분모 $P(B)$ 는 사건 $B$가 발생했을 경우를 의미하며, 표본공간이 $\Omega$에서 사건 $B$로 축소됩니다. 

이와 같은 조건부 확률을 조금 더 깊이 살펴봅시다.


## 전확률 공식

예를 들어 처음 개업시 하나의 공장을 운영하다 사업이 번창함에 따라 공장을 순차적으로 공장을 열어 현재 3곳의 공장을 운영하고 있습니다. 이 회사는 품질에 관심이 많아 공장별로 품질관리를 진행하고 있습니다.
세 공장은 매 주 단위로 불량률을 점검하면서 기기의 상태와 원재료 관리등을 수행하고 있습니다. 세 공장으로부터 불량률을 보고 받던 이사회에서는 개별 공장의 불량이 아닌 회사 공정의 불량률이 얼마나 될지 알아보고자 합니다.

여기서 각 공장의 불량률의 평균으로 전체 불량을 구할 수 있을까요? 
생산하는 물량도 서로 다르고, 생산 환경도 다르기에 평균을 이용하지 않습니다.

### 분할(Partition)
표본공간 $\Omega$ 상의 사건 $A_{1}, A_{2}, ..., A_{n}$은 서로 배반이고, $A_{1} \cup A_{2} \cup , ...A_{n-1} \cup A_{n} = \Omega$ 일 때, $A_{1}, A_{2}, ..., A_{n}$ 을 표본공간의 분할이라고 합니다.

앞선 예에서 각 공장별로 생산하는 제품은 서로 겹치지 않고(배반이고) 공장별 생산제품을 모두 합하면 전체 생산제품일 것입니다. 즉, 각 공장은 회사에서 생산하는 제품의 분할입니다.

### 전확률 공식

여기서 전체 공장에서 발생하는 불량율은 얼마일까요?
불량이 발생하는 사건을 $B$라고 하면, 사건 $B$의 확률 $P(B)$를 구하면 될 것입니다.

다음은 전체 생산품을 생산한 공장으로 분할하고, 불량이라는 사건을 나타낸 것입니다.


여기서 불량인 사건 B는 첫번째 공장($A_{1}$)에서 발생한 불량, 두번째 공장($A_{2}$)에서 발생한 불량, 세번째 공장($A_{1}$)에서 발생한 불량들의 합집합입니다.

<p align="center">$B = (B \cap A_{1}) \cup (B \cap A_{2}) \cup (B \cap A_{3})$</p>

불량의 확률 $P(B)$ 는, 

<p align="center">$P(B) = P[ (B \cap A_{1}) \cup (B \cap A_{2}) \cup (B \cap A_{3})  ]$</p>

여기서 각 공장에서 불량이 발생하는 것은 배반이므로, 

\begin{align*}
P(B) & =  P(B \cap A_{1}) + P(B \cap A_{2}) + P(B \cap A_{3}) \\
& =  \sum_{i = 1}^{3} P(B \cap A_{i})
\end{align*}

와 같으며, 조건부 확률 $P(A | B) = \frac{P(A \cap B)}{P(B)}$ 에서 $P(A \cap B) = P(B)P(A|B)$ 이므로, 위의 식은

\begin{align*}
\sum_{i = 1}^{3} P(B \cap A_{i}) & = \sum_{i = 1}^{3} P(A_{i})P(B|A_{i}) 
\end{align*}

이므로,

<p align="center">$P(B) = \sum_{i = 1}^{3} P(A_{i})P(B|A_{i})$</p>

이며, 이를 확률 B에 대한 전확률 공식이라고 합니다.
